export interface ImageManifest {
    name: string;
    sheet: number;
    row: number;
    column: number;
}

export { image_manifest };

var image_manifest_str = `[{"sheet": 0, "name": "A06_HeadCamera", "row": 0, "column": 0}, {"sheet": 0, "name": "A07_UnicornHornHair", "row": 0, "column": 1}, {"sheet": 0, "name": "A08_Headphones", "row": 0, "column": 2}, {"sheet": 0, "name": "A08_Headphones_Sn_FG", "row": 0, "column": 3}, {"sheet": 0, "name": "A09_RainbowWig", "row": 1, "column": 0}, {"sheet": 0, "name": "A09_RainbowWig_Sn_FG", "row": 1, "column": 1}, {"sheet": 0, "name": "A10_CowboyHat", "row": 1, "column": 2}, {"sheet": 0, "name": "A10_CowboyHat_Sn", "row": 1, "column": 3}, {"sheet": 0, "name": "A11_TopHat", "row": 2, "column": 0}, {"sheet": 0, "name": "A11_TopHat_Sn_FG", "row": 2, "column": 1}, {"sheet": 0, "name": "A12_FlameTiara", "row": 2, "column": 2}, {"sheet": 0, "name": "A12_FlameTiara_Sn", "row": 2, "column": 3}, {"sheet": 0, "name": "A13_TropicalTiara", "row": 3, "column": 0}, {"sheet": 0, "name": "A13_TropicalTiara_Sn", "row": 3, "column": 1}, {"sheet": 0, "name": "A14_CarrotNose", "row": 3, "column": 2}, {"sheet": 0, "name": "A15_3dGlasses", "row": 3, "column": 3}, {"sheet": 1, "name": "A15_3dGlasses_Sn", "row": 0, "column": 0}, {"sheet": 1, "name": "A16_SnowboarderGlasses", "row": 0, "column": 1}, {"sheet": 1, "name": "A16_SnowboarderGlasses_Sn", "row": 0, "column": 2}, {"sheet": 1, "name": "A17_MoneyGlasses", "row": 0, "column": 3}, {"sheet": 1, "name": "A17_MoneyGlasses_Sn", "row": 1, "column": 0}, {"sheet": 1, "name": "A18_Love-U-Glasses_Sn", "row": 1, "column": 1}, {"sheet": 1, "name": "A19_Monocle", "row": 1, "column": 2}, {"sheet": 1, "name": "A19_Monocle_Sn", "row": 1, "column": 3}, {"sheet": 1, "name": "A20_Steampunk", "row": 2, "column": 0}, {"sheet": 1, "name": "A20_Steampunk_Sn", "row": 2, "column": 1}, {"sheet": 1, "name": "A21_FruitFacial", "row": 2, "column": 2}, {"sheet": 1, "name": "A22_HornsBeard", "row": 2, "column": 3}, {"sheet": 1, "name": "A23_Mustache", "row": 3, "column": 0}, {"sheet": 1, "name": "A24_CocoaMug", "row": 3, "column": 1}, {"sheet": 1, "name": "A25_SelfieCamera", "row": 3, "column": 2}, {"sheet": 1, "name": "A25_SelfieCamera_Sn", "row": 3, "column": 3}, {"sheet": 2, "name": "A26_FairySweater_Armsdown", "row": 0, "column": 0}, {"sheet": 2, "name": "A26_FairySweater_Sn", "row": 0, "column": 1}, {"sheet": 2, "name": "A27_PoofJacket_Sn_FG", "row": 0, "column": 2}, {"sheet": 2, "name": "A27_PoofyJacket", "row": 0, "column": 3}, {"sheet": 2, "name": "A28_FannyPack", "row": 1, "column": 0}, {"sheet": 2, "name": "A28_FannyPack_Sn_FG", "row": 1, "column": 1}, {"sheet": 2, "name": "A29_InflatableFlamingo", "row": 1, "column": 2}, {"sheet": 2, "name": "A29_InflatableFlamingo_Sn_FG", "row": 1, "column": 3}, {"sheet": 2, "name": "A31_Scarf", "row": 2, "column": 0}, {"sheet": 2, "name": "A31_Scarf_Sn", "row": 2, "column": 1}, {"sheet": 2, "name": "A32_Vest", "row": 2, "column": 2}, {"sheet": 2, "name": "A32_Vest_Sn_FG", "row": 2, "column": 3}, {"sheet": 2, "name": "A33_SnoweeMug_Alt5", "row": 3, "column": 0}]`;

var image_manifest = JSON.parse(image_manifest_str) as ImageManifest[];